<?php


/**
 * @see http://drupal.org/project/history_rec
 */

/**
 * Implements hook_help().
 */
function history_rec_help($path, $args) {
  $output = '';
  switch ($path) {
    case "admin/help#history_rec":
      $output = '<p>'.  t("This module generates node recommendations based on user browsing history") .'</p>';
      break;
  }
  return $output;
}

/**
 * Implements hook_menu().
 */ 
function history_rec_menu() {
  $items = array();
  $items['admin/config/recommender/history_rec'] = array(
    'title' => 'Browsing History Recommender',
    'description' => 'Configure the Browsing History Recommender',
    'page callback' => 'drupal_get_fodrrm',
    'page arguments' => array('history_rec_settings_form'),
    'access arguments' => array('administer recommender'),
    'file' => 'history_rec.admin.inc'
  );
  return $items;
}

/**
 * Implements hook_views_api().
 */
function history_rec_views_api() {
  return array(
    'api' => 3,
  );
}
